os: linux
dist: focal
language: csharp
mono: none
dotnet: 3.1
before_install:
- sudo apt-get -y install libpam0g-dev
- sudo useradd -p $(python3 -c 'import crypt; print(crypt.crypt("pwd123"))') userxyz
install:
- dotnet restore
script:
- dotnet test
