os: linux
dist: focal
language: csharp
mono: none
dotnet: 3.1
before_install:
- sudo apt-get -y install libpam0g-dev
install:
- dotnet restore
script:
- dotnet build -c Release
after_script:
- ./test/setup_test_account.sh && dotnet test test/Npam.Tests/Npam.Tests.csproj -v d
